spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jarvis_dev
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

endpoint:
  metrics:
    enabled: true

katharsis:
  resourcePackage: com.creditcards.jarvis.web
  domainName: http://localhost:8080
  pathPrefix: /api
